linters:
  enable:
    - gci
    - gofumpt
    - govet
    - misspell
    - nolintlint
  disable:
    - errcheck
    - unused

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/containernetworking/plugins)
