linters:
  enable:
    - gci
    - gofmt
    - govet
    - misspell
    - nolintlint

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/containernetworking/plugins)
